#!/usr/bin/env python3
"""Render one sample's assessment results as Markdown for readers.

Usage: summary.py <assessment-results.json> <rules.csv> <component-definition.json> <sample>

Rolls rule verdicts up to controls using rules.csv: a control is satisfied for the
sample only if every rule mapped to it passed; any failure makes it not satisfied; a
rule that evaluated nothing makes it not evaluated. Lists every control the component
definition claims that no rule checks.
"""
import csv
import json
import re
import sys

from verdicts import control_verdict, label, rule_verdicts


def sort_key(cid):
    m = re.fullmatch(r"([a-z]{2})-(\d+)(?:\.(\d+))?", cid)
    return m.group(1), int(m.group(2)), int(m.group(3) or 0)


def load_rules(path):
    with open(path) as f:
        return [{"id": r["rule_id"], "description": r["rule_description"], "controls": r["control_ids"].split(),
                 "note": r["evidence_note"]} for r in csv.DictReader(f)]


def claimed(compdef):
    ids = set()
    for comp in compdef["component-definition"]["components"]:
        for impl in comp.get("control-implementations", []):
            ids |= {r["control-id"] for r in impl.get("implemented-requirements", [])}
    return ids


def render(ar_root, rules, compdef, sample):
    verdicts = rule_verdicts(ar_root)
    by_control = {}
    for r in rules:
        for cid in r["controls"]:
            by_control.setdefault(cid, []).append(r["id"])
    limited = {cid for r in rules if r["note"] for cid in r["controls"]}
    lines = [f"# Kyverno evaluation: {sample} samples", "",
             f"Generated by `scripts/summary.py` from `assessment-results.json`. This is evidence about the manifests "
             f"in `samples/{sample}/`, evaluated offline with the Kyverno CLI. It is not an assessment of any system.",
             "", "## Controls with offline checks", "",
             "| Control | Result for these samples | Rules |", "|---|---|---|"]
    for cid in sorted(by_control, key=sort_key):
        vs = [verdicts.get(rid, {}).get("verdict", "none") for rid in by_control[cid]]
        rules_cell = "; ".join(f"`{rid}`: {v}" for rid, v in zip(by_control[cid], vs))
        verdict = control_verdict(vs)
        if verdict == "satisfied" and cid in limited:
            verdict = "satisfied, with limits (see below)"
        lines.append(f"| {label(cid)} | {verdict} | {rules_cell} |")
    lines += ["", "## Rules", "", "| Rule | Controls | Verdict | Resources evaluated |", "|---|---|---|---:|"]
    for r in sorted(rules, key=lambda r: r["id"]):
        v = verdicts.get(r["id"], {"verdict": "none", "subjects": []})
        # One subject per (object, rule inside the policy): count each object once.
        evaluated = len({t for t, res, _ in v["subjects"] if res in ("pass", "fail", "warn", "error")})
        lines.append(f"| `{r['id']}` | {', '.join(label(c) for c in r['controls'])} | {v['verdict']} | {evaluated} |")
    failures = [(rid, t, why) for rid, v in sorted(verdicts.items())
                for t, res, why in v["subjects"] if res in ("fail", "warn", "error")]
    if failures:
        lines += ["", "## Failures", ""]
        lines += [f"- `{rid}` on {t}: {why}" for rid, t, why in failures]
    notes = [(r["controls"], r["note"]) for r in rules if r["note"]]
    if notes:
        lines += ["", "## What the evidence does not show", ""]
        lines += [f"- {', '.join(label(c) for c in cs)}: {note}" for cs, note in notes]
    unchecked = sorted(claimed(compdef) - set(by_control), key=sort_key)
    lines += ["", "## Claimed controls with no offline check", "",
              f"{len(unchecked)} controls the component definition claims have no rule here, because they depend on "
              "apiserver configuration, TLS, key management, network behaviour, change process, inventory, or "
              "application code. They need configuration review or live evidence:", "",
              ", ".join(label(c) for c in unchecked), ""]
    return "\n".join(lines)


def main(ar_path, rules_csv, compdef_path, sample):
    with open(ar_path) as a, open(compdef_path) as c:
        print(render(json.load(a), load_rules(rules_csv), json.load(c), sample), end="")


if __name__ == "__main__":
    main(*sys.argv[1:5])
