#!/usr/bin/env python3
"""Gap report: the controls a resolved profile selects that a component definition does
not claim.

Usage: gap.py <resolved-profile.json> <component-definition.json> [<mapping.csv>]

Works with any component definition, including your own platform's. With this
repository's mapping CSV it also annotates the External controls with the category of
component that closes each one.

Selected controls fall into four sets:
  claimed      implemented by some component, fully
  partial      implemented, but the component marks its coverage partial
  external     mapped in the CSV as needing a component upstream software does not supply
  unmapped     outside the mapping's scope; split by NIST implementation level, since
               organization-level controls (policy, personnel, physical) are rarely a
               platform's to claim and system-level ones usually are
"""
import csv
import json
import re
import sys
from collections import Counter, defaultdict

NS = "https://northfleetsecurity.ca/ns/oscal/cccs"


def prop(c, name):
    return next((p["value"] for p in c.get("props", []) if p["name"] == name), None)


def label(c):
    return next((p["value"] for p in c.get("props", []) if p["name"] == "label" and "class" not in p),
                c["id"].upper())


def title(c):
    return prop(c, "cccs-title") or c["title"]


def oid(lab):
    m = re.fullmatch(r"([A-Z]{2})-(\d+)(?:\((\d+)\))?", lab.strip())
    return f"{m.group(1).lower()}-{int(m.group(2))}" + (f".{int(m.group(3))}" if m.group(3) else "")


def main(resolved_path, compdef_path, mapping_path=None):
    cat = json.load(open(resolved_path))["catalog"]
    selected = {}

    def walk(cs):
        for c in cs:
            if prop(c, "status") != "withdrawn" and prop(c, "cccs-status") != "withdrawn":
                selected[c["id"]] = c
            walk(c.get("controls", []))
    for g in cat.get("groups", []):
        walk(g.get("controls", []))
    walk(cat.get("controls", []))

    cd = json.load(open(compdef_path))["component-definition"]
    claims = defaultdict(list)   # control-id -> [(component, partial)]
    for comp in cd.get("components", []):
        for impl in comp.get("control-implementations", []):
            for req in impl.get("implemented-requirements", []):
                partial = any(p["name"] == "coverage" and p["value"] == "partial" for p in req.get("props", []))
                claims[req["control-id"]].append((comp["title"], partial))

    external = {}
    if mapping_path:
        for r in csv.DictReader(open(mapping_path)):
            if r["Category"] == "External":
                external[oid(r["Control"])] = r["K8s Mechanism"].strip()

    claimed = {i for i in selected if claims.get(i) and not all(p for _, p in claims[i])}
    partial = {i for i in selected if claims.get(i) and all(p for _, p in claims[i])}
    ext = {i for i in selected if i in external and i not in claimed | partial}
    unmapped = set(selected) - claimed - partial - ext
    level = {i: prop(selected[i], "implementation-level") or
             ("canada-specific" if selected[i].get("class", "").startswith("cccs") else "unspecified")
             for i in unmapped}
    order = list(selected)

    def rows(ids):
        return [i for i in order if i in ids]

    profile_title = cat["metadata"]["title"]
    out = [f"# Gap report: {cd['metadata']['title']}", "",
           f"Profile: {profile_title}  ",
           f"Component definition: {cd['metadata']['title']} ({cd['metadata']['version']})", "",
           "Generated by `scripts/gap.py`. A claim is what a component can implement, not an assessment of any "
           "system.", "",
           "| Set | Controls |", "|---|---:|",
           f"| Selected by the profile (excluding withdrawn) | {len(selected)} |",
           f"| Claimed by a component | {len(claimed)} |",
           f"| Claimed with partial coverage | {len(partial)} |",
           f"| External: needs a component upstream software does not supply | {len(ext)} |",
           f"| Outside the mapping's scope, system-level | {sum(1 for v in level.values() if v == 'system')} |",
           f"| Outside the mapping's scope, organization-level | {sum(1 for v in level.values() if v == 'organization')} |",
           f"| Outside the mapping's scope, Canada-specific | {sum(1 for v in level.values() if v == 'canada-specific')} |",
           f"| Outside the mapping's scope, level not stated | {sum(1 for v in level.values() if v == 'unspecified')} |",
           ""]
    if ext:
        out += ["## External", "", "Selected, and upstream Kubernetes cannot satisfy them on its own.", "",
                "| Control | Title | What closes it |", "|---|---|---|"]
        out += [f"| {label(selected[i])} | {title(selected[i])} | {external[i]} |" for i in rows(ext)]
        out.append("")
    if partial:
        out += ["## Partial", "", "Claimed, with part of the control left to another component.", "",
                "| Control | Title | Claimed by | Remainder |", "|---|---|---|---|"]
        out += [f"| {label(selected[i])} | {title(selected[i])} | {', '.join(t for t, _ in claims[i])} | "
                f"{external.get(i, '')} |" for i in rows(partial)]
        out.append("")
    sys_level = [i for i in rows(unmapped) if level[i] in ("system", "canada-specific", "unspecified")]
    if sys_level:
        out += ["## Outside the mapping's scope: system-level and Canada-specific", "",
                "Candidates for the next revision of the mapping.", "",
                "| Control | Title | Level |", "|---|---|---|"]
        out += [f"| {label(selected[i])} | {title(selected[i])} | {level[i]} |" for i in sys_level]
        out.append("")
    org = Counter(i.split("-")[0].upper() for i in unmapped if level[i] == "organization")
    if org:
        out += ["## Outside the mapping's scope: organization-level, by family", "",
                "| Family | Controls |", "|---|---:|"]
        out += [f"| {f} | {n} |" for f, n in sorted(org.items())]
        out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main(*sys.argv[1:4])
